name: Update Forms JSON

on:
  workflow_dispatch:
    inputs:
      formData:
        description: "Form data JSON"
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update FormFieldsInfo.json
        run: |
          echo '${{ inputs.formData }}' > formData.json

          # Load the existing FormFieldsInfo.json
          existingJson=$(cat src/data/FormFieldsInfo.json)

          # Load the new form data
          newFormData=$(cat formData.json)

          # Get the id from the new form data (assuming the id is the first key in the object)
          formId=$(echo "$newFormData" | jq -r 'keys[0]')

          # Check if the id exists in the existing JSON and update or append
          if echo "$existingJson" | jq -e "has($formId)" > /dev/null; then
            # If the ID exists, update the corresponding object
            updatedJson=$(echo "$existingJson" | jq --argjson newForm "$newFormData" ". + $newForm")
          else
            # If the ID doesn't exist, append the new object
            updatedJson=$(echo "$existingJson" | jq --argjson newForm "$newFormData" ". + $newForm")
          fi

          # Save the updated JSON back to FormFieldsInfo.json
          echo "$updatedJson" > src/data/FormFieldsInfo.json

          # Display the updated JSON for verification
          cat src/data/FormFieldsInfo.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add src/data/FormFieldsInfo.json
          git commit -m "Updated FormFieldsInfo.json with new or updated submission"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
