name: Update Forms JSON

on:
  workflow_dispatch:
    inputs:
      formData:
        description: "Form data JSON"
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Append New Form to FormFieldsInfo.json
        run: |
          echo '${{ inputs.formData }}' > formData.json
          jq --argjson newForm "$(cat formData.json)" '. += $newForm' src/Utils/FormFieldsInfo.json > tmp.json && mv tmp.json src/Utils/FormFieldsInfo.json
          cat src/Utils/FormFieldsInfo.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add src/Utils/FormFieldsInfo.json
          git commit -m "Updated FormFieldsInfo.json with new submission"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
